services:
  postgres:
    image: postgres:16
    container_name: fraud-spike-detector-postgres
    restart: always
    environment:
      POSTGRES_USER: fraud_user
      POSTGRES_PASSWORD: fraud_pass
      POSTGRES_DB: fraud_spike_detector
    ports:
      - "5433:5432"     
    volumes:
      - fraud_postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: fraud-spike-detector-redis
    restart: always
    ports:
      - "6380:6379"    
    volumes: []

volumes:
  fraud_postgres_data: