"""add transaction risk fields

Revision ID: 0f4f54d33807
Revises: 
Create Date: 2026-08-26 22:20:28.820299

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f4f54d33807'
down_revision: Union[str, Sequence[str], None] = '3c574408c3e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('risk_score', sa.Float(), nullable=True))
    op.add_column('transactions', sa.Column('risk_decision', sa.String(length=20), nullable=True))
    op.add_column('transactions', sa.Column('risk_reasons', sa.JSON(), nullable=True))
    op.create_index(op.f('ix_transactions_risk_decision'), 'transactions', ['risk_decision'], unique=False)
    


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transactions_risk_decision'), table_name='transactions')
    op.drop_column('transactions', 'risk_reasons')
    op.drop_column('transactions', 'risk_decision')
    op.drop_column('transactions', 'risk_score')
    # ### end Alembic commands ###
