"""add transaction review audit fields

Revision ID: b4a70bbf15b8
Revises: 8b00205ee47c
Create Date: 2026-08-28 04:25:59.880988

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b4a70bbf15b8'
down_revision: Union[str, Sequence[str], None] = '8b00205ee47c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('reviewed_by', sa.Integer(), nullable=True))
    op.add_column('transactions', sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_transactions_reviewed_by'), 'transactions', ['reviewed_by'], unique=False)
    op.create_foreign_key(None, 'transactions', 'users', ['reviewed_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_index(op.f('ix_transactions_reviewed_by'), table_name='transactions')
    op.drop_column('transactions', 'reviewed_at')
    op.drop_column('transactions', 'reviewed_by')
    # ### end Alembic commands ###
